development:
  adapter: sqlite3
  database: /home/hu/projects/booker/db/booker.db
  pool: 5
  timeout: 5000

production:
  adapter: mysql
  encoding: utf8
  database: booker
  username: root
  password: steve

